name: stream_weather
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:

  dio: ^5.3.2
  
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1  
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0

dependency_overrides:
  win32: ^5.5.4

flutter:


